version: '3.7'

services:
#  api:
#    hostname: plusone-api
#    container_name: plusone-api
#    image: plusone/api:latest
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    entrypoint: ["java","-jar","/app.jar"]
#    ports:
#      - "9000:9000"
#    env_file: ./.env

  mysql:
    image: mysql:8.0.25
    platform: linux/amd64
    hostname: plusone
    container_name: plusone
    ports:
      - '23306:3306'
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=plusone
      - MYSQL_ROOT_PASSWORD=password