server.port : 9000
spring:
  mvc:
    view:
      - prefix:/static/
      - suffix:.html
      - static-path-pattern: /resources/**
#  application:
#    name: acorn
#  profiles:
#    active: local
#  config:
#    import:
#      - classpath:/config/custom/custom.yml
#      - classpath:/config/custom/el.yml
#  h2:
#    console:
#      enabled: true                     # ?? ??
#      path: /h2-console                 # ?? ?? uri
#      settings.trace: false             # ?? ???
#      settings.web-allow-others: false  # CORS? ?? ??? ?? ?? ??
  datasource:
    url: jdbc:mysql://data/gs25db     # ?? ???
    username: sa
    password: rama112
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource  # ? ?? HikariDataSource? ?? ??? ???? ????? ??
    hikari:                             # DB Connection Pool
      auto-commit: true                 # ???? ??. (default: true)
      connection-test-query: SELECT 1   # connection ??? ?? ??
      pool-name: pool-acorn            # connection pool ??
      leak-detection-threshold: 300000
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 10                  # pool? ??? ?? connection ?? ??
      maximum-pool-size: 50             # pool? ???? ? ?? ?? connection ?
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect  # ??? database? SQL Dialect ??, JPA? ???? ?? ?? ???, database? ?? ?? sql? ??
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true                  # ?? SQL?? ??? ??
        format_sql: true                # ?? SQL?? ??? ??? ??.
        hbm2ddl.auto: update            # ? ??? @Entity? ??? ???? ????? Update
        highlight_sql: true
        use_sql_comments: true          # ???? ????? SQL? ??? ???? ??? ??